import { useEffect, useState } from 'react';
import { Fish, X, BarChart3, MapPin, Thermometer, Waves, Zap } from 'lucide-react';

const API = import.meta.env.VITE_FISH_API_BASE_URL || 'http://localhost:8001';

type Meta = { regions:string[]; species:string[]; pfz:any[] };
type Result = any;

const Bar=({items}:{items:{label:string,value:number}[]})=><div className="space-y-2">{items.slice(0,10).map(x=><div key={x.label}><div className="flex justify-between text-[11px] text-slate-400"><span>{x.label}</span><span>{x.value.toLocaleString()}</span></div><div className="mt-1 h-2 rounded bg-slate-800"><div className="h-full rounded bg-cyan-500" style={{width:`${Math.min(100,(x.value/Math.max(...items.map(i=>i.value),1))*100)}%`}}/></div></div>)}</div>;

export default function FishProductivityPanel(){
 const [open,setOpen]=useState(false),[meta,setMeta]=useState<Meta>({regions:[],species:[],pfz:[]}),[mode,setMode]=useState('region'),[region,setRegion]=useState(''),[species,setSpecies]=useState('All'),[compare,setCompare]=useState(''),[lat,setLat]=useState(13),[lon,setLon]=useState(80.3),[pfz,setPfz]=useState(''),[data,setData]=useState<Result|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!open||meta.regions.length)return;fetch(`${API}/api/fish-productivity/regions`).then(r=>r.json()).then(d=>{setMeta(d);setRegion(d.regions?.[0]||'');setPfz(d.pfz?.[0]?.id||'')}).catch(e=>setError(e.message));},[open,meta.regions.length]);
 const run=async()=>{setLoading(true);setError('');try{const body:any={mode,region,species,compare_region:compare||null};if(mode==='coordinate')Object.assign(body,{lat,lon});if(mode==='pfz')body.pfz_id=pfz;const r=await fetch(`${API}/api/fish-productivity/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.detail||'Analysis failed');setData(d)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const total=data?.years?.reduce((s:number,x:any)=>s+x.catch,0)||0,latest=data?.years?.at(-1)?.catch||0;
 return <><button onClick={()=>setOpen(true)} className="fixed left-0 top-1/2 z-[1500] -translate-y-1/2 rounded-r-xl border border-cyan-500/30 bg-slate-950/95 px-3 py-3 text-xs font-bold text-cyan-300 shadow-2xl"><Fish className="inline h-4 w-4 mr-2"/>FISH PRODUCTIVITY</button>
 {open&&<div className="fixed inset-y-0 left-0 z-[2000] w-[min(96vw,1080px)] overflow-hidden border-r border-slate-700 bg-slate-950 shadow-2xl">
 <header className="flex items-center justify-between border-b border-slate-800 p-5"><div className="flex gap-3 items-center"><Fish className="text-cyan-300"/><div><h2 className="font-bold text-lg text-slate-100">Fish Productivity Analytics</h2><p className="text-xs text-slate-500">Catch × SST × chlorophyll × PFZ intelligence</p></div></div><button onClick={()=>setOpen(false)}><X className="text-slate-400"/></button></header>
 <main className="h-[calc(100%-76px)] overflow-y-auto p-5 space-y-5">
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap gap-2 mb-4">{[['region','Region'],['coordinate','Latitude / Longitude'],['pfz','PFZ']].map(([k,l])=><button key={k} onClick={()=>setMode(k)} className={`px-3 py-2 rounded-lg text-xs ${mode===k?'bg-cyan-500/15 text-cyan-300':'text-slate-400 bg-slate-950'}`}>{l}</button>)}</div><div className="grid md:grid-cols-4 gap-3">{mode==='region'&&<label className="text-xs text-slate-400">Region<select value={region} onChange={e=>setRegion(e.target.value)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded p-2 text-slate-100">{meta.regions.map(r=><option key={r}>{r}</option>)}</select></label>}{mode==='coordinate'&&<><label className="text-xs text-slate-400">Latitude<input type="number" step=".0001" value={lat} onChange={e=>setLat(+e.target.value)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded p-2 text-slate-100"/></label><label className="text-xs text-slate-400">Longitude<input type="number" step=".0001" value={lon} onChange={e=>setLon(+e.target.value)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded p-2 text-slate-100"/></label></>}{mode==='pfz'&&<label className="text-xs text-slate-400 md:col-span-2">Potential Fishing Zone<select value={pfz} onChange={e=>setPfz(e.target.value)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded p-2 text-slate-100">{meta.pfz.map(p=><option key={p.id} value={p.id}>{p.coast} • {p.state} • {Number(p.lat).toFixed(2)}, {Number(p.lon).toFixed(2)}</option>)}</select></label>}<label className="text-xs text-slate-400">Fish type<select value={species} onChange={e=>setSpecies(e.target.value)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded p-2 text-slate-100"><option>All</option>{meta.species.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs text-slate-400">Compare region<select value={compare} onChange={e=>setCompare(e.target.value)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded p-2 text-slate-100"><option value="">None</option>{meta.regions.map(r=><option key={r}>{r}</option>)}</select></label></div><button onClick={run} disabled={loading} className="mt-4 rounded-lg bg-cyan-600 px-4 py-2 text-sm font-semibold">{loading?'Analyzing…':'Analyze productivity'}</button>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}</section>
 {data&&<><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[[<Fish/>, 'Total catch',total],[<BarChart3/>,'Latest year',latest],[<Thermometer/>,'Avg SST',data.environment?.length?`${(data.environment.filter((x:any)=>x.sst!=null).reduce((s:number,x:any)=>s+x.sst,0)/Math.max(1,data.environment.filter((x:any)=>x.sst!=null).length)).toFixed(2)} °C`:'—'],[<Waves/>,'Avg chlorophyll',data.environment?.length?`${(data.environment.filter((x:any)=>x.chlorophyll!=null).reduce((s:number,x:any)=>s+x.chlorophyll,0)/Math.max(1,data.environment.filter((x:any)=>x.chlorophyll!=null).length)).toFixed(3)}`:'—']].map((x:any)=><div key={x[1]} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="text-slate-500 text-xs flex justify-between">{x[1]}{x[0]}</div><b className="text-xl text-slate-100">{x[2]}</b></div>)}</div>
 <section className="grid lg:grid-cols-2 gap-5"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-semibold mb-4">Catch over years</h3><Bar items={data.years.map((x:any)=>({label:String(x.year),value:x.catch}))}/></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-semibold mb-4">Fish types</h3><Bar items={data.species.map((x:any)=>({label:x.species,value:x.catch}))}/></div></section>
 <section className="grid lg:grid-cols-2 gap-5"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-semibold mb-4">Seasonal analysis</h3><Bar items={data.seasonal.map((x:any)=>({label:x.season,value:x.catch}))}/></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-semibold mb-4">SST / chlorophyll trend</h3>{data.environment.slice(-12).map((x:any)=><div key={x.year} className="grid grid-cols-3 gap-2 text-xs py-1"><span>{x.year}</span><span className="text-orange-300">SST {x.sst?.toFixed(2)??'—'}</span><span className="text-teal-300">Chl {x.chlorophyll?.toFixed(3)??'—'}</span></div>)}</div></section>
 <section className="grid lg:grid-cols-2 gap-5"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-semibold mb-3">Chlorophyll heatmap</h3><Heat points={data.heatmaps?.chlorophyll||[]}/></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-semibold mb-3">SST heatmap</h3><Heat points={data.heatmaps?.sst||[]}/></div></section>
 <section className="grid lg:grid-cols-2 gap-5"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-semibold mb-3">Correlation</h3><p className="text-sm text-teal-300">Catch ↔ chlorophyll: {data.correlation?.catch_chlorophyll?.toFixed(2)??'—'}</p><p className="text-sm text-orange-300 mt-2">Catch ↔ SST: {data.correlation?.catch_sst?.toFixed(2)??'—'}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-semibold mb-3">Anomaly detection</h3>{data.anomalies?.length?data.anomalies.map((a:any)=><p key={a.year} className="text-xs text-amber-300">{a.year}: z-score {a.catch_anomaly.toFixed(2)}</p>):<p className="text-sm text-slate-500">No ±2σ catch anomalies.</p>}</div></section>
 {data.comparison&&<section className="rounded-2xl border border-indigo-500/20 bg-indigo-500/5 p-4"><h3 className="font-semibold">Region vs region</h3><p className="text-sm text-slate-300">{data.selection.target_region} vs {data.comparison.region}</p><div className="mt-3 grid md:grid-cols-2 gap-4"><Bar items={data.years.map((x:any)=>({label:`${x.year} selected`,value:x.catch}))}/><Bar items={data.comparison.years.map((x:any)=>({label:`${x.year} comparison`,value:x.catch}))}/></div></section>}
 <section className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-4"><h3 className="flex gap-2 items-center font-semibold text-cyan-200"><Zap className="h-4 w-4"/> Why productivity changed</h3><p className="mt-2 text-sm text-slate-300">{data.explanation}</p></section></>}
 </main></div>}</>;
}

function Heat({points}:{points:any[]}){if(!points.length)return <div className="h-48 flex items-center justify-center text-sm text-slate-500">No environmental grid available.</div>;const vals=points.map(p=>p.value),mn=Math.min(...vals),mx=Math.max(...vals,mn+1e-9),la=points.map(p=>p.lat),lo=points.map(p=>p.lon),lam=Math.min(...la),lax=Math.max(...la),lom=Math.min(...lo),lox=Math.max(...lo);return <div className="relative h-48 rounded-xl border border-slate-800 bg-slate-950 overflow-hidden">{points.slice(0,300).map((p,i)=>{const x=(p.lon-lom)/Math.max(1e-9,lox-lom)*100,y=(1-(p.lat-lam)/Math.max(1e-9,lax-lam))*100,o=.15+(p.value-mn)/Math.max(1e-9,mx-mn)*.85;return <span key={i} title={`${p.lat}, ${p.lon}: ${p.value}`} className="absolute h-3 w-3 rounded-full bg-emerald-300" style={{left:`${x}%`,top:`${y}%`,opacity:o}}/>})}</div>}
